on:
  workflow_dispatch:
#  push:

name: Calculate bluefish temperature indicators

jobs:

  build1:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
#        with:
#          persist-credentials: false

      - name: Install command line packages
        run: |
          sudo apt update
          sudo apt-get install  libgdal-dev libcurl4-gnutls-dev libgit2-dev libudunits2-dev libharfbuzz-dev libfribidi-dev
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0.3' # problem with using 4.0.4

      - name: Cache R packages
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ env.R_LIBS_USER }}
          key: bluefish-cache

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Rscript -e '
          install.packages(c("ncdf4", "knitr", "usethis", "raster", "rgdal",
          "here", "devtools", "dplyr", "sf", "ggplot2", "reshape2", "stringr"))
          devtools::install_github("NOAA-EDAB/ecodata")
          devtools::install_github("NOAA-EDAB/NEesp")
          devtools::install_github("kimberly-bastille/ecopull")'

      - name: Calculate indicators
        run: |
          Rscript -e '
          options(timeout = 60 * 60 * 6)
          install.packages("readxl")
          install.packages("Rcpp")
          install.packages("terra", repos='https://rspatial.r-universe.dev')
          install.packages("raster")
          try(source(here::here("temperature.R")))'

      - name: Check directory size
        run: |
          du -s
          cd data-raw
          du -s
        shell: bash

      - name: Send to repo
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # The branch the action should deploy to.
          folder: data-raw # The folder the action should deploy
          target-folder: data-raw
          clean: false # Automatically remove deleted files from the deploy branch
